[project]
name = "lm-reasoner"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = ["psycopg[binary]>=3.2"]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"
