[project]
name = "lm-templates"
version = "0.1.0"
dependencies = ["beautifulsoup4", "requests" , "openai==1.81.0"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["lm_templates*"]
